name: rakuraku
description: "rakuraku"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI 관련 패키지
  cupertino_icons: ^1.0.8

  # 라우팅
  go_router: ^13.2.2

  # 네트워크 통신
  dio: ^5.7.0

  # 상태관리
  flutter_bloc: ^8.1.3

  # 코드 생성
  freezed_annotation: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^4.2.1
  fpdart: ^1.1.1
  flutter_cache_manager: ^3.4.1
  retrofit: ^4.4.2
  logger: ^2.5.0
  json_annotation: ^4.9.0
  http: ^1.2.2
  mockito: ^5.4.5
  json_serializable: ^6.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # 코드 생성 도구
  freezed: ^2.4.7
  build_runner: ^2.4.8
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true